name: Gaming Bot Auto Post
on:
  schedule:
    - cron: '0 10 * * *'  # Dopahar 3:30 PM (IST)
    - cron: '0 16 * * *'  # Raat 9:30 PM (IST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Run Bot
        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python final_bot.py
